### ISSUE TITLE
Is it possible to sign up/create/register a new user in Cognito using this library?

### ISSUE THREAD

**Issue by Miguelme** [markomirosavljev/fastapi-cognito#10]
Is it possible to sign up/create/register a new user in Cognito using this library? It seems to me it would be a huge impact to be able to register new users easily directly from this library

**Comment by markomirosavljev** [comment]
Hello, with this library you can only validate and decode JWT from AWS Cognito. You can use [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html) to do that.
