### ISSUE TITLE
Support for FastAPI v0.112.x

### ISSUE THREAD

**Issue by YaraslauZhylko** [markomirosavljev/fastapi-cognito#25]
FastAPI v0.112.0 has been released.
While `fastapi-cognito` still requires `fastapi (>=0.111.0,<0.112.0)`.

Should probably increase the supported range.

**Comment by guy-ecton** [comment]
This library doesn't even use `fastapi` (it is only imported in `example.py`). So the dependency can be removed, changed to `*` or moved to "dev dependencies".

**Comment by KAEYL98** [comment]
Hi, bumping this as `fastapi` is now at `0.115.0`. Thanks

**Comment by markomirosavljev** [comment]
Hello everyone :wave: and sorry for waiting this much.

 I just released updated version. You will be able to use >=0.111.0 < 1.0.0 versions of `fastapi`. 

Regarding the removing `fastapi` from dependencies, It does actually use `HTTPException` provided by fastapi in [fastapi_cognito.py](https://github.com/markomirosavljev/fastapi-cognito/blob/main/src/fastapi_cognito/fastapi_cognito.py#L3) so I will leave it here for now.
