### ISSUE TITLE
login redirect?

### ISSUE THREAD

**Issue by JustinGuese** [markomirosavljev/fastapi-cognito#5]
nice stuff, as I found the fastapi-cloudauth not nice... But how would I redirect someone to the login page if not auth?
I have a Fastapi serving HTML files, how do I do the login with your library?

**Comment by markomirosavljev** [comment]
Hello, thank you for feedback. I'm not sure I clearly understand your problem. Library is built with primary focus on REST API endpoints auth and token decoding-validation. It is not possible to login with library.

**Comment by JustinGuese** [comment]
yeah, that's what i figured, no worries!
