### ISSUE TITLE
Feature request: Add support of multiple app_client_ids per User Pool

### ISSUE THREAD

**Issue by tivaliy** [markomirosavljev/fastapi-cognito#8]
Hi, first of all thanks a lot for this library.

I have a quick question/feature request. Is there any chance to add support of multiple `app_client_id` per User Pool. At least this one is supported by the library you are using [cognitojwt](https://github.com/borisrozumnuk/cognitojwt).

Tanks in advance.

**Comment by markomirosavljev** [comment]
Hello and thanks for feedback. I think it is possible so I will add that feature soon.

**Comment by markomirosavljev** [comment]
Hello, I just released new version with support for multiple userpool `app_client_ids` - [check here.](https://github.com/markomirosavljev/fastapi-cognito/releases/tag/v.2.3.0)
